const fs=require('fs'),path=require('path');
const DATA={"Ajmer":["Ajmer","Kishangarh","Nasirabad","Pushkar","Kekri","Sarwar"],"Alwar":["Alwar","Rajgarh","Ramgarh","Thanagazi","Laxmangarh"],"Balotra":["Balotra","Pachpadra","Siwana","Samdari"],"Banswara":["Banswara","Kushalgarh","Bagidora","Ghatol","Garhi"],"Baran":["Baran","Anta","Atru","Chhabra","Mangrol","Shahbad"],"Barmer":["Barmer","Chohtan","Dhorimanna","Gudamalani","Sheo"],"Beawar":["Beawar","Masuda","Vijaynagar","Raipur","Jaitaran"],"Bharatpur":["Bharatpur","Bayana","Nadbai","Weir","Roopwas"],"Bhilwara":["Bhilwara","Shahpura","Asind","Mandal","Mandalgarh","Jahazpur","Gulabpura"],"Bikaner":["Bikaner","Nokha","Deshnoke","Lunkaransar","Kolayat","Khajuwala"],"Bundi":["Bundi","Lakheri","Keshoraipatan","Nainwa","Hindoli","Indragarh"],"Chittorgarh":["Chittorgarh","Nimbahera","Kapasan","Begun","Rawatbhata","Bari Sadri"],"Churu":["Churu","Ratangarh","Sujangarh","Sardarshahar","Taranagar","Rajgarh"],"Dausa":["Dausa","Bandikui","Lalsot","Mahwa","Sikrai"],"Deeg":["Deeg","Kaman","Nagar","Kumher","Pahari"],"Dholpur":["Dholpur","Bari","Rajakhera","Baseri"],"Didwana-Kuchaman":["Didwana","Kuchaman City","Ladnun","Makrana","Parbatsar","Nawa"],"Dungarpur":["Dungarpur","Sagwara","Aspur","Simalwara"],"Hanumangarh":["Hanumangarh","Nohar","Bhadra","Pilibanga","Sangaria","Rawatsar"],"Jaipur":["Jaipur","Chomu","Sambhar","Phulera","Shahpura","Jobner","Dudu","Kishangarh Renwal"],"Jaisalmer":["Jaisalmer","Pokaran","Fatehgarh"],"Jalore":["Jalore","Bhinmal","Sanchore","Raniwara","Ahore"],"Jhalawar":["Jhalawar","Bhawani Mandi","Jhalrapatan","Aklera","Khanpur","Manohar Thana"],"Jhunjhunu":["Jhunjhunu","Nawalgarh","Chirawa","Pilani","Khetri","Mandawa","Udaipurwati"],"Jodhpur":["Jodhpur","Bilara","Pipar City","Bhopalgarh","Osian"],"Karauli":["Karauli","Hindaun","Todabhim","Sapotra"],"Khairthal-Tijara":["Khairthal","Tijara","Bhiwadi","Kishangarh Bas","Mundawar"],"Kota":["Kota","Ramganj Mandi","Sangod","Itawa"],"Kotputli-Behror":["Kotputli","Behror","Neemrana","Bansur","Viratnagar","Paota"],"Nagaur":["Nagaur","Merta City","Degana","Jayal","Khinvsar"],"Pali":["Pali","Sojat","Bali","Sumerpur","Marwar Junction","Desuri"],"Phalodi":["Phalodi","Lohawat","Dechu","Bap"],"Pratapgarh":["Pratapgarh","Chhoti Sadri","Arnod","Dhariawad"],"Rajsamand":["Rajsamand","Nathdwara","Amet","Deogarh","Bhim","Kumbhalgarh"],"Salumber":["Salumber","Sarada","Semari","Jhallara","Lasadiya"],"Sawai Madhopur":["Sawai Madhopur","Gangapur City","Bonli","Chauth Ka Barwara"],"Sikar":["Sikar","Fatehpur","Neem Ka Thana","Sri Madhopur","Lachhmangarh","Reengus"],"Sirohi":["Sirohi","Abu Road","Mount Abu","Pindwara","Sheoganj"],"Sri Ganganagar":["Sri Ganganagar","Suratgarh","Raisinghnagar","Sri Karanpur","Sadulshahar","Anupgarh"],"Tonk":["Tonk","Malpura","Niwai","Deoli","Todaraisingh","Uniara"],"Udaipur":["Udaipur","Fatehnagar","Bhinder","Gogunda","Kherwara","Mavli"]};
const CAT_ALIASES={"Photographers & Films":["photographers & films","photographers","photography & films"],"Mehendi Artists":["mehendi artists","mehndi artists"],"DJ & Entertainment":["dj & entertainment","dj and entertainment"],"Decorators & Tent House":["decorators & tent house","decorators and tent house"],"Anchors & Emcees":["anchors & emcees","anchors and emcees"]};
const CATS=[["Wedding Venues","wedding-venues"],["Photographers & Films","photographers-films"],["Makeup Artists","makeup-artists"],["Decorators & Tent House","decorators-tent-house"],["Wedding Planners","wedding-planners"],["Caterers","caterers"],["Mehendi Artists","mehendi-artists"],["DJ & Entertainment","dj-entertainment"],["Anchors & Emcees","anchors-emcees"],["Wedding Rental Dresses","wedding-rental-dresses"],["Bridal Wear","bridal-wear"],["Groom Wear","groom-wear"],["Band, Dhol & Ghodi","band-dhol-ghodi"],["Pandit & Wedding Priest","pandit-wedding-priest"],["Other Wedding Service","other-wedding-service"]];
const API='https://script.google.com/macros/s/AKfycbz8SfXfcYwH5giymrCmKOGf9w_kmXjXGBiQ6CtrI2Btl7K3zDja5xcLGOwSEtD-XwM8eg/exec',ROOT='https://rajasthanweddingguide.com/rajasthan/';
const slug=s=>s.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;');
const css='body{margin:0;font-family:Arial,sans-serif;background:#f7f3eb;color:#171717}a{color:#76571f;text-decoration:none}header,footer{background:#0b0b0b;color:#fff;padding:22px 6%}.wrap{max-width:1100px;margin:auto;padding:40px 6%}.hero{background:#111;color:#fff;border-radius:20px;padding:38px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:15px;margin-top:25px}.card{background:#fff;padding:20px;border-radius:15px}.dev{background:#fff1c9;padding:12px;margin-top:20px;border-radius:10px}';
function crumbs(a){return {'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':a.map((x,i)=>({'@type':'ListItem','position':i+1,'name':x[0],'item':x[1]}))}}
function html(title,desc,canon,h1,nav,body,cr){return '<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>'+esc(title)+'</title><meta name="description" content="'+esc(desc)+'"><link rel="canonical" href="'+canon+'"><style>'+css+'</style><script type="application/ld+json">'+JSON.stringify(crumbs(cr))+'</script></head><body><header><b>Rajasthan Wedding Guide</b></header><main class="wrap"><nav>'+nav+'</nav><section class="hero"><h1>'+h1+'</h1><p>'+desc+'</p></section>'+body+'<div class="dev">DEV SEO system • noindex until production approval</div></main><footer>© 2026 Rajasthan Wedding Guide</footer></body></html>'}
function put(file,content){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,content)}
fs.rmSync('rajasthan',{recursive:true,force:true});
const districts=Object.keys(DATA);
put('rajasthan/index.html',html('Wedding Vendors in Rajasthan | Rajasthan Wedding Guide','Explore wedding vendors across Rajasthan by district, city and category.',ROOT,'Wedding Vendors in Rajasthan','Rajasthan','<section class="grid">'+districts.map(d=>'<a class="card" href="./'+slug(d)+'/">'+d+'</a>').join('')+'</section>',[['Rajasthan',ROOT]]));
let cities=0,pages=1;
for(const d of districts){const ds=slug(d),du=ROOT+ds+'/';put('rajasthan/'+ds+'/index.html',html('Wedding Vendors in '+d+' | Rajasthan Wedding Guide','Find wedding vendors across '+d+' district, Rajasthan. Browse by city or town and wedding service category.',du,'Wedding Vendors in '+d,'<a href="'+ROOT+'">Rajasthan</a> → '+d,'<section class="grid">'+DATA[d].map(c=>'<a class="card" href="./'+slug(c)+'/">'+c+'</a>').join('')+'</section>',[['Rajasthan',ROOT],[d,du]]));pages++;
for(const c of DATA[d]){cities++;const cs=slug(c),cu=du+cs+'/';put('rajasthan/'+ds+'/'+cs+'/index.html',html('Wedding Vendors in '+c+', '+d+' | Rajasthan Wedding Guide','Find wedding vendors in '+c+', '+d+', Rajasthan. Browse photographers, venues, makeup artists, decorators, caterers and more.',cu,'Wedding Vendors in '+c+', '+d,'<a href="'+ROOT+'">Rajasthan</a> → <a href="'+du+'">'+d+'</a> → '+c,'<section class="grid">'+CATS.map(x=>'<a class="card" href="./'+x[1]+'/">'+x[0]+'</a>').join('')+'</section>',[['Rajasthan',ROOT],[d,du],[c,cu]]));pages++;
for(const [cat,cs2] of CATS){const u=cu+cs2+'/',desc='Find approved '+cat.toLowerCase()+' in '+c+', '+d+', Rajasthan. Explore services and vendor profiles on Rajasthan Wedding Guide.';const js="<script>const CAT_ALIASES="+JSON.stringify(CAT_ALIASES)+";</script><section><h2>Approved "+cat+" in "+c+"</h2><div class=grid id=v><div class=card>Loading approved vendors…</div></div></section><script>fetch('"+API+"?action=list&_='+Date.now(),{cache:'no-store'}).then(r=>r.json()).then(j=>{let n=s=>String(s||'').trim().toLowerCase(),p=(o,a,b)=>o[a]??o[b]??'',a=(j.items||[]).filter(x=>n(p(x,'Status','status'))==='approved'&&n(p(x,'District','district'))===n('"+d+"')&&n(p(x,'City','city'))===n('"+c+"')&&((CAT_ALIASES['"+cat+"']||['"+cat+"']).map(n).includes(n(p(x,'Category','category')))));document.getElementById('v').innerHTML=a.length?a.map(x=>'<article class=card><b>'+p(x,'Business Name','businessName')+'</b><p>'+p(x,'Services','services')+'</p><a href=../../../../vendor.html?id='+encodeURIComponent(p(x,'Submission ID','id'))+'>View Profile →</a></article>').join(''):'<div class=card>No approved vendors listed yet.</div>'})</script>";put('rajasthan/'+ds+'/'+cs+'/'+cs2+'/index.html',html(cat+' in '+c+', '+d+' | Rajasthan Wedding Guide',desc,u,cat+' in '+c+', '+d,'<a href="'+ROOT+'">Rajasthan</a> → <a href="'+du+'">'+d+'</a> → <a href="'+cu+'">'+c+'</a> → '+cat,js,[['Rajasthan',ROOT],[d,du],[c,cu],[cat,u]]));pages++}}}
console.log(JSON.stringify({districts:districts.length,cities,pages,categories:CATS.length}));
const urls=[ROOT];
for(const d of Object.keys(DATA)){const du=ROOT+slug(d)+'/';urls.push(du);for(const city of DATA[d]){const cu=du+slug(city)+'/';urls.push(cu);for(const [,catSlug] of CATS)urls.push(cu+catSlug+'/')}}
const sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>'  <url><loc>'+u+'</loc></url>').join('\n')+'\n</urlset>\n';
fs.writeFileSync('sitemap-seo.xml',sitemap);
fs.writeFileSync('robots-dev.txt','User-agent: *\nDisallow: /rajasthan/\n# DEV safety: generated SEO pages remain noindex,nofollow and are not submitted to search engines.\n');
console.log(JSON.stringify({districts:Object.keys(DATA).length,cities,pages,categories:CATS.length,sitemapUrls:urls.length,indexing:'NOINDEX DEV'}));
const legacyMap={
"didwana.html":{action:"MIGRATE_AFTER_LIVE",target:"/rajasthan/didwana-kuchaman/didwana/"},
"didwana-photographers.html":{action:"MIGRATE_AFTER_LIVE",target:"/rajasthan/didwana-kuchaman/didwana/photographers-films/"},
"didwana-makeup-artists.html":{action:"MIGRATE_AFTER_LIVE",target:"/rajasthan/didwana-kuchaman/didwana/makeup-artists/"},
"didwana-rental-dresses.html":{action:"MIGRATE_AFTER_LIVE",target:"/rajasthan/didwana-kuchaman/didwana/wedding-rental-dresses/"},
"didwana-venues.html":{action:"MIGRATE_AFTER_LIVE",target:"/rajasthan/didwana-kuchaman/didwana/wedding-venues/"},
"photographers-approved.html":{action:"MIGRATE_AFTER_LIVE",target:"/rajasthan/didwana-kuchaman/didwana/photographers-films/"},
"photographers.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"makeup-artists.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"venues.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"rental-dresses.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"caterers.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"decorators.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"dj-entertainment.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"mehendi-artists.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"wedding-planners.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"anchors-emcees.html":{action:"KEEP_STATE_CATEGORY",reason:"Rajasthan-wide category intent; do not redirect to generic state hub."},
"categories.html":{action:"KEEP_NAV_HUB"},
"cities.html":{action:"KEEP_NAV_HUB"}
};
fs.writeFileSync('legacy-seo-map.json',JSON.stringify({policy:"REVIEW_BEFORE_PRODUCTION",note:"No legacy redirect is activated by this file. City-level legacy URLs migrate only after destination pages are live and verified. Rajasthan-wide category hubs remain category-specific.",mappings:legacyMap},null,2)+"\n");
